FROM python:3.11-slim
WORKDIR /app
RUN pip install uv
COPY pyproject.toml .
RUN uv pip install --system -r pyproject.toml
COPY . .

CMD ["celery", "-A", "app.infra.celery_app", "worker", "--loglevel=info"]